package cv.lecturesight.setup;

/**
 *
 * @author wulff
 */
public class CameraCalibrationPanel extends javax.swing.JPanel {

  /**
   * Creates new form CameraCalibrationPanel
   */
  public CameraCalibrationPanel() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    cameraControlPanel = new javax.swing.JPanel();
    videoFrameHolder = new javax.swing.JPanel();
    verticalControlsPanel = new javax.swing.JPanel();
    upButton = new javax.swing.JButton();
    downButton = new javax.swing.JButton();
    fastDownButton = new javax.swing.JButton();
    fastUpButton = new javax.swing.JButton();
    horizontalControlsPanel = new javax.swing.JPanel();
    fastLeftButton = new javax.swing.JButton();
    leftButton = new javax.swing.JButton();
    rightButton = new javax.swing.JButton();
    fastRightButton = new javax.swing.JButton();
    homeButtonPanel = new javax.swing.JPanel();
    homeButton = new javax.swing.JButton();
    boundsPanel4 = new javax.swing.JPanel();
    leftBoundButton4 = new javax.swing.JButton();
    rightBoundButton4 = new javax.swing.JButton();
    leftBoundText4 = new javax.swing.JTextField();
    rightBoundText4 = new javax.swing.JTextField();
    upperBoundButton4 = new javax.swing.JButton();
    upperBoundText4 = new javax.swing.JTextField();
    bottomBoundButton4 = new javax.swing.JButton();
    bottomBoundText4 = new javax.swing.JTextField();
    dialogControlsPanel = new javax.swing.JPanel();
    saveButton = new javax.swing.JButton();
    cancelButton = new javax.swing.JButton();

    cameraControlPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Production Camera", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

    videoFrameHolder.setBackground(new java.awt.Color(1, 1, 1));

    javax.swing.GroupLayout videoFrameHolderLayout = new javax.swing.GroupLayout(videoFrameHolder);
    videoFrameHolder.setLayout(videoFrameHolderLayout);
    videoFrameHolderLayout.setHorizontalGroup(
      videoFrameHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );
    videoFrameHolderLayout.setVerticalGroup(
      videoFrameHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );

    upButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow-090.png"))); // NOI18N
    upButton.setToolTipText("turn camera up");

    downButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow-270.png"))); // NOI18N
    downButton.setToolTipText("turn camera down");

    fastDownButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow-skip-270.png"))); // NOI18N
    fastDownButton.setToolTipText("turn camera down fast");

    fastUpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow-skip-090.png"))); // NOI18N
    fastUpButton.setToolTipText("turn camera up fast");

    javax.swing.GroupLayout verticalControlsPanelLayout = new javax.swing.GroupLayout(verticalControlsPanel);
    verticalControlsPanel.setLayout(verticalControlsPanelLayout);
    verticalControlsPanelLayout.setHorizontalGroup(
      verticalControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(verticalControlsPanelLayout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addGroup(verticalControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(upButton, javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(downButton, javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(fastDownButton, javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(fastUpButton, javax.swing.GroupLayout.Alignment.TRAILING)))
    );
    verticalControlsPanelLayout.setVerticalGroup(
      verticalControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(verticalControlsPanelLayout.createSequentialGroup()
        .addComponent(fastUpButton)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(upButton)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(downButton)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(fastDownButton)
        .addContainerGap(96, Short.MAX_VALUE))
    );

    fastLeftButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow-skip-180.png"))); // NOI18N
    fastLeftButton.setToolTipText("turn camera left fast");

    leftButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow-180.png"))); // NOI18N
    leftButton.setToolTipText("turn camera left");

    rightButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow.png"))); // NOI18N
    rightButton.setToolTipText("turn camera right");

    fastRightButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow-skip.png"))); // NOI18N
    fastRightButton.setToolTipText("turn camera right fast");

    javax.swing.GroupLayout horizontalControlsPanelLayout = new javax.swing.GroupLayout(horizontalControlsPanel);
    horizontalControlsPanel.setLayout(horizontalControlsPanelLayout);
    horizontalControlsPanelLayout.setHorizontalGroup(
      horizontalControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(horizontalControlsPanelLayout.createSequentialGroup()
        .addComponent(fastLeftButton)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(leftButton)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(rightButton)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(fastRightButton)
        .addGap(0, 0, Short.MAX_VALUE))
    );
    horizontalControlsPanelLayout.setVerticalGroup(
      horizontalControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, horizontalControlsPanelLayout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addGroup(horizontalControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(fastLeftButton)
          .addComponent(leftButton)
          .addComponent(rightButton)
          .addComponent(fastRightButton)))
    );

    homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow-in.png"))); // NOI18N
    homeButton.setToolTipText("turn camera to home position");

    javax.swing.GroupLayout homeButtonPanelLayout = new javax.swing.GroupLayout(homeButtonPanel);
    homeButtonPanel.setLayout(homeButtonPanelLayout);
    homeButtonPanelLayout.setHorizontalGroup(
      homeButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeButtonPanelLayout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(homeButton))
    );
    homeButtonPanelLayout.setVerticalGroup(
      homeButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeButtonPanelLayout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(homeButton))
    );

    javax.swing.GroupLayout cameraControlPanelLayout = new javax.swing.GroupLayout(cameraControlPanel);
    cameraControlPanel.setLayout(cameraControlPanelLayout);
    cameraControlPanelLayout.setHorizontalGroup(
      cameraControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cameraControlPanelLayout.createSequentialGroup()
        .addGroup(cameraControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(horizontalControlsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(videoFrameHolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(cameraControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(verticalControlsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(homeButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
    );
    cameraControlPanelLayout.setVerticalGroup(
      cameraControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(cameraControlPanelLayout.createSequentialGroup()
        .addGap(2, 2, 2)
        .addGroup(cameraControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(videoFrameHolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(verticalControlsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(cameraControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(homeButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(horizontalControlsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
    );

    boundsPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bounds", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

    leftBoundButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow-stop-180.png"))); // NOI18N
    leftBoundButton4.setToolTipText("set left bound");

    rightBoundButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow-stop.png"))); // NOI18N
    rightBoundButton4.setToolTipText("set right bound");

    leftBoundText4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        leftBoundText4ActionPerformed(evt);
      }
    });

    upperBoundButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow-stop-090.png"))); // NOI18N
    upperBoundButton4.setToolTipText("set top bound");

    bottomBoundButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow-stop-270.png"))); // NOI18N
    bottomBoundButton4.setToolTipText("set bottom bound");
    bottomBoundButton4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        bottomBoundButton4ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout boundsPanel4Layout = new javax.swing.GroupLayout(boundsPanel4);
    boundsPanel4.setLayout(boundsPanel4Layout);
    boundsPanel4Layout.setHorizontalGroup(
      boundsPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(boundsPanel4Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(boundsPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(boundsPanel4Layout.createSequentialGroup()
            .addComponent(rightBoundButton4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(rightBoundText4, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
          .addGroup(boundsPanel4Layout.createSequentialGroup()
            .addComponent(leftBoundButton4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(leftBoundText4)))
        .addGap(18, 18, 18)
        .addGroup(boundsPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(upperBoundButton4)
          .addComponent(bottomBoundButton4))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(boundsPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(upperBoundText4, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
          .addComponent(bottomBoundText4))
        .addContainerGap())
    );
    boundsPanel4Layout.setVerticalGroup(
      boundsPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(boundsPanel4Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(boundsPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(leftBoundButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(leftBoundText4)
          .addComponent(upperBoundButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(upperBoundText4))
        .addGap(13, 13, 13)
        .addGroup(boundsPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(rightBoundText4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(boundsPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
            .addComponent(bottomBoundButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bottomBoundText4))
          .addComponent(rightBoundButton4))
        .addContainerGap(16, Short.MAX_VALUE))
    );

    saveButton.setText("Save");

    cancelButton.setText("Cancel");

    javax.swing.GroupLayout dialogControlsPanelLayout = new javax.swing.GroupLayout(dialogControlsPanel);
    dialogControlsPanel.setLayout(dialogControlsPanelLayout);
    dialogControlsPanelLayout.setHorizontalGroup(
      dialogControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogControlsPanelLayout.createSequentialGroup()
        .addContainerGap(492, Short.MAX_VALUE)
        .addComponent(cancelButton)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(saveButton)
        .addContainerGap())
    );
    dialogControlsPanelLayout.setVerticalGroup(
      dialogControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogControlsPanelLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(dialogControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(saveButton)
          .addComponent(cancelButton))
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(cameraControlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(boundsPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(dialogControlsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(cameraControlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(boundsPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(dialogControlsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void leftBoundText4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftBoundText4ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_leftBoundText4ActionPerformed

  private void bottomBoundButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottomBoundButton4ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_bottomBoundButton4ActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton bottomBoundButton;
  private javax.swing.JButton bottomBoundButton1;
  private javax.swing.JButton bottomBoundButton2;
  private javax.swing.JButton bottomBoundButton3;
  private javax.swing.JButton bottomBoundButton4;
  private javax.swing.JTextField bottomBoundText;
  private javax.swing.JTextField bottomBoundText1;
  private javax.swing.JTextField bottomBoundText2;
  private javax.swing.JTextField bottomBoundText3;
  private javax.swing.JTextField bottomBoundText4;
  private javax.swing.JPanel boundsPanel;
  private javax.swing.JPanel boundsPanel1;
  private javax.swing.JPanel boundsPanel2;
  private javax.swing.JPanel boundsPanel3;
  private javax.swing.JPanel boundsPanel4;
  private javax.swing.JPanel cameraControlPanel;
  private javax.swing.JButton cancelButton;
  private javax.swing.JPanel dialogControlsPanel;
  private javax.swing.JButton downButton;
  private javax.swing.JButton fastDownButton;
  private javax.swing.JButton fastLeftButton;
  private javax.swing.JButton fastRightButton;
  private javax.swing.JButton fastUpButton;
  private javax.swing.JButton homeButton;
  private javax.swing.JPanel homeButtonPanel;
  private javax.swing.JPanel horizontalControlsPanel;
  private javax.swing.JButton leftBoundButton;
  private javax.swing.JButton leftBoundButton1;
  private javax.swing.JButton leftBoundButton2;
  private javax.swing.JButton leftBoundButton3;
  private javax.swing.JButton leftBoundButton4;
  private javax.swing.JTextField leftBoundText;
  private javax.swing.JTextField leftBoundText1;
  private javax.swing.JTextField leftBoundText2;
  private javax.swing.JTextField leftBoundText3;
  private javax.swing.JTextField leftBoundText4;
  private javax.swing.JButton leftButton;
  private javax.swing.JButton rightBoundButton;
  private javax.swing.JButton rightBoundButton1;
  private javax.swing.JButton rightBoundButton2;
  private javax.swing.JButton rightBoundButton3;
  private javax.swing.JButton rightBoundButton4;
  private javax.swing.JTextField rightBoundText;
  private javax.swing.JTextField rightBoundText1;
  private javax.swing.JTextField rightBoundText2;
  private javax.swing.JTextField rightBoundText3;
  private javax.swing.JTextField rightBoundText4;
  private javax.swing.JButton rightButton;
  private javax.swing.JButton saveButton;
  private javax.swing.JButton upButton;
  private javax.swing.JButton upperBoundButton;
  private javax.swing.JButton upperBoundButton1;
  private javax.swing.JButton upperBoundButton2;
  private javax.swing.JButton upperBoundButton3;
  private javax.swing.JButton upperBoundButton4;
  private javax.swing.JTextField upperBoundText;
  private javax.swing.JTextField upperBoundText1;
  private javax.swing.JTextField upperBoundText2;
  private javax.swing.JTextField upperBoundText3;
  private javax.swing.JTextField upperBoundText4;
  private javax.swing.JPanel verticalControlsPanel;
  private javax.swing.JPanel videoFrameHolder;
  // End of variables declaration//GEN-END:variables
}
