site_name: LectureSight Guide
repo_url: https://bitbucket.org/bwulff/lecturesight/

# Default theme used is readthedocs
theme:
  name:  material
  logo:  'images/lecturesight.png'

# The directory that contain the source .md files
docs_dir: 'docs'

# The directory to which the site is built using mkdocs
site_dir: 'site'

# This needs to be listed in order to populate the left navigation and the TOC
# Items will appear in this order

pages:
- Home: 'index.md'

#- Release Notes: 'releasenotes.md'
#- Upgrade: 'upgrade.md'
#- Changelog: 'changelog.md'
#
- Hardware:
   - Server: 'hardware/server.md'
   - Overview Camera: 'hardware/overview-camera.md'
   - PTZ Camera: 'hardware/ptz-camera.md'

- Installation:
   - Overview: 'install/index.md'
   - Dependencies: 'install/dependencies.md'

#   - Installation from Source:
#      - Linux: 'installation/source-linux.md'
#- Configuration:
#

- Core Services:
    - 'OpenCL': 'core/opencl.md'
    - 'Heartbeat': 'core/heartbeat.md'
    - 'Frame Source': 'core/framesource.md'
    - 'Scene Profile': 'core/profile.md'
    - 'Video Analysis' : 'core/videoanalysis-templ.md'
    - 'Scheduler' : 'core/scheduler.md'
    - 'Console': 'core/console.md'
    - 'Metrics': 'core/metrics.md'

- 'Modules':
    - 'Pan-Only Camera Operator' : 'modules/cameraoperator-simple.md'
    - 'Relative Move Steering Worker': 'modules/steeringworker-relativemove.md'
    - 'Dummy Camera': 'modules/ptzcontrol-dummy.md'
    - 'VAPIX Camera': 'modules/ptzcontrol-vapix.md'
    - 'VISCA Camera': 'modules/ptzcontrol-visca.md'
    - 'ONVIF Camera': 'modules/ptzcontrol-onvif.md'

- User Interface:
    - 'Overview Camera': 'ui/overview.md'
    - 'Scene Profile Editor': 'ui/profile.md'
    - 'Object Tracker': 'ui/objecttracker.md'
    - 'PTZ Camera Control': 'ui/cameracontrol.md'
    - 'System Configuration': 'ui/config.md'

- Development:
    - 'Style Guide': 'develop/style.md'
