site_name: Lecturesight Guide
repo_url: https://bitbucket.org/bwulff/lecturesight/

# Default theme used is readthedocs
theme: readthedocs

# The directory that contain the source .md files
docs_dir: 'docs'

# The directory to which the site is built using mkdocs
site_dir: 'site'

# This needs to be listed in order to populate the left navigation and the TOC
# Items will appear in this order

pages:
- Home: 'index.md'

#- Release Notes: 'releasenotes.md'
#- Upgrade: 'upgrade.md'
#- Changelog: 'changelog.md'
#
#- Installation:
#   - Overview: 'installation/index.md'
#   - Installation from Source:
#      - Linux: 'installation/source-linux.md'
#- Configuration:
#

- Modules:
    - 'Frame Source': 'modules/framesource.md'
    - 'Pan-Only Camera Operator' : 'modules/cameraoperator-simple.md'
    - 'Relative Move Steering Worker': 'modules/steeringworker-relativemove.md'
    - 'Dummy Camera': modules/ptzcontrol-dummy.md
    - 'VAPIX Camera': 'modules/ptzcontrol-vapix.md'
    - 'Video Analysis' : 'modules/videoanalysis-templ.md'
    - 'Scheduler' : 'modules/scheduler.md'

- User Interface:
    - 'Object Tracker': 'ui/objecttracker.md'
    - 'PTZ Camera Control': 'ui/cameracontrol.md'
    - 'Scene Profile Editor': 'ui/profile.md'
