/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cv_lecturesight_ptz_visca_VISCACamera */

#ifndef _Included_cv_lecturesight_ptz_visca_VISCACamera
#define _Included_cv_lecturesight_ptz_visca_VISCACamera
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cv_lecturesight_ptz_visca_VISCACamera
 * Method:    getConnectedCams
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cv_lecturesight_ptz_visca_VISCACamera_getConnectedCams
  (JNIEnv *, jobject);

/*
 * Class:     cv_lecturesight_ptz_visca_VISCACamera
 * Method:    initialize
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_cv_lecturesight_ptz_visca_VISCACamera_initialize
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     cv_lecturesight_ptz_visca_VISCACamera
 * Method:    deinitialize
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cv_lecturesight_ptz_visca_VISCACamera_deinitialize
  (JNIEnv *, jobject);

/*
 * Class:     cv_lecturesight_ptz_visca_VISCACamera
 * Method:    setPower
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_cv_lecturesight_ptz_visca_VISCACamera_setPower
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     cv_lecturesight_ptz_visca_VISCACamera
 * Method:    isPowerOn
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cv_lecturesight_ptz_visca_VISCACamera_isPowerOn
  (JNIEnv *, jobject);

/*
 * Class:     cv_lecturesight_ptz_visca_VISCACamera
 * Method:    setPanSpeed
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_cv_lecturesight_ptz_visca_VISCACamera_setPanSpeed
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cv_lecturesight_ptz_visca_VISCACamera
 * Method:    setTiltSpeed
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_cv_lecturesight_ptz_visca_VISCACamera_setTiltSpeed
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cv_lecturesight_ptz_visca_VISCACamera
 * Method:    setZoomSpeed
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_cv_lecturesight_ptz_visca_VISCACamera_setZoomSpeed
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cv_lecturesight_ptz_visca_VISCACamera
 * Method:    getPanSpeed
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_cv_lecturesight_ptz_visca_VISCACamera_getPanSpeed
  (JNIEnv *, jobject);

/*
 * Class:     cv_lecturesight_ptz_visca_VISCACamera
 * Method:    getTiltSpeed
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_cv_lecturesight_ptz_visca_VISCACamera_getTiltSpeed
  (JNIEnv *, jobject);

/*
 * Class:     cv_lecturesight_ptz_visca_VISCACamera
 * Method:    getZoomSpeed
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_cv_lecturesight_ptz_visca_VISCACamera_getZoomSpeed
  (JNIEnv *, jobject);

/*
 * Class:     cv_lecturesight_ptz_visca_VISCACamera
 * Method:    backlight
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_cv_lecturesight_ptz_visca_VISCACamera_backlight
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     cv_lecturesight_ptz_visca_VISCACamera
 * Method:    isBacklight
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cv_lecturesight_ptz_visca_VISCACamera_isBacklight
  (JNIEnv *, jobject);

/*
 * Class:     cv_lecturesight_ptz_visca_VISCACamera
 * Method:    zoomIn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cv_lecturesight_ptz_visca_VISCACamera_zoomIn
  (JNIEnv *, jobject);

/*
 * Class:     cv_lecturesight_ptz_visca_VISCACamera
 * Method:    zoomOut
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cv_lecturesight_ptz_visca_VISCACamera_zoomOut
  (JNIEnv *, jobject);

/*
 * Class:     cv_lecturesight_ptz_visca_VISCACamera
 * Method:    stopZoom
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cv_lecturesight_ptz_visca_VISCACamera_stopZoom
  (JNIEnv *, jobject);

/*
 * Class:     cv_lecturesight_ptz_visca_VISCACamera
 * Method:    getZoom
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_cv_lecturesight_ptz_visca_VISCACamera_getZoom
  (JNIEnv *, jobject);

/*
 * Class:     cv_lecturesight_ptz_visca_VISCACamera
 * Method:    setZoom
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_cv_lecturesight_ptz_visca_VISCACamera_setZoom
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cv_lecturesight_ptz_visca_VISCACamera
 * Method:    move
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_cv_lecturesight_ptz_visca_VISCACamera_move
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     cv_lecturesight_ptz_visca_VISCACamera
 * Method:    moveDown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cv_lecturesight_ptz_visca_VISCACamera_moveDown
  (JNIEnv *, jobject);

/*
 * Class:     cv_lecturesight_ptz_visca_VISCACamera
 * Method:    moveUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cv_lecturesight_ptz_visca_VISCACamera_moveUp
  (JNIEnv *, jobject);

/*
 * Class:     cv_lecturesight_ptz_visca_VISCACamera
 * Method:    moveLeft
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cv_lecturesight_ptz_visca_VISCACamera_moveLeft
  (JNIEnv *, jobject);

/*
 * Class:     cv_lecturesight_ptz_visca_VISCACamera
 * Method:    moveRight
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cv_lecturesight_ptz_visca_VISCACamera_moveRight
  (JNIEnv *, jobject);

/*
 * Class:     cv_lecturesight_ptz_visca_VISCACamera
 * Method:    stopMove
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cv_lecturesight_ptz_visca_VISCACamera_stopMove
  (JNIEnv *, jobject);

/*
 * Class:     cv_lecturesight_ptz_visca_VISCACamera
 * Method:    getFocus
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_cv_lecturesight_ptz_visca_VISCACamera_getFocus
  (JNIEnv *, jobject);

/*
 * Class:     cv_lecturesight_ptz_visca_VISCACamera
 * Method:    setFocus
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_cv_lecturesight_ptz_visca_VISCACamera_setFocus
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     cv_lecturesight_ptz_visca_VISCACamera
 * Method:    focusFar
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cv_lecturesight_ptz_visca_VISCACamera_focusFar
  (JNIEnv *, jobject);

/*
 * Class:     cv_lecturesight_ptz_visca_VISCACamera
 * Method:    focusNear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cv_lecturesight_ptz_visca_VISCACamera_focusNear
  (JNIEnv *, jobject);

/*
 * Class:     cv_lecturesight_ptz_visca_VISCACamera
 * Method:    focusStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cv_lecturesight_ptz_visca_VISCACamera_focusStop
  (JNIEnv *, jobject);

/*
 * Class:     cv_lecturesight_ptz_visca_VISCACamera
 * Method:    setAutoFocus
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_cv_lecturesight_ptz_visca_VISCACamera_setAutoFocus
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     cv_lecturesight_ptz_visca_VISCACamera
 * Method:    isAutoFocusSet
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cv_lecturesight_ptz_visca_VISCACamera_isAutoFocusSet
  (JNIEnv *, jobject);

/*
 * Class:     cv_lecturesight_ptz_visca_VISCACamera
 * Method:    getPan
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_cv_lecturesight_ptz_visca_VISCACamera_getPan
  (JNIEnv *, jobject);

/*
 * Class:     cv_lecturesight_ptz_visca_VISCACamera
 * Method:    getTilt
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_cv_lecturesight_ptz_visca_VISCACamera_getTilt
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
