package cv.lecturesight.framesource.impl.ui;

import cv.lecturesight.display.Display;
import java.awt.BorderLayout;
import javax.swing.UIManager;

public class FrameSourceProviderUIPanel extends javax.swing.JPanel {

  private Display display;
  
  /** Creates new form FrameSourceProviderUIPanel */
  public FrameSourceProviderUIPanel(Display display) {
    this.display = display;
    // set operating system look-and-feel
    try {
      UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
    } catch (Exception e) {
    }
    initComponents();
    displayContainer.setLayout(new BorderLayout());
    displayContainer.add(display.getDisplayPanel(), BorderLayout.CENTER);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    inputPanel = new javax.swing.JPanel();
    mrlLabel = new javax.swing.JLabel();
    mrlText = new javax.swing.JTextField();
    displayContainer = new javax.swing.JPanel();

    inputPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

    mrlLabel.setText("MRL:");

    mrlText.setEditable(false);
    mrlText.setText("v4l:///dev/video0[width=640;height=400]");

    javax.swing.GroupLayout displayContainerLayout = new javax.swing.GroupLayout(displayContainer);
    displayContainer.setLayout(displayContainerLayout);
    displayContainerLayout.setHorizontalGroup(
      displayContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 388, Short.MAX_VALUE)
    );
    displayContainerLayout.setVerticalGroup(
      displayContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 244, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout inputPanelLayout = new javax.swing.GroupLayout(inputPanel);
    inputPanel.setLayout(inputPanelLayout);
    inputPanelLayout.setHorizontalGroup(
      inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(inputPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(mrlLabel)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(mrlText, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
        .addContainerGap())
      .addComponent(displayContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    inputPanelLayout.setVerticalGroup(
      inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputPanelLayout.createSequentialGroup()
        .addComponent(displayContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(mrlText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(mrlLabel)))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(inputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(inputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel displayContainer;
  private javax.swing.JPanel inputPanel;
  private javax.swing.JLabel mrlLabel;
  private javax.swing.JTextField mrlText;
  // End of variables declaration//GEN-END:variables
}
