package cv.lecturesight.manpages;

import javax.swing.text.html.HTMLEditorKit;
import javax.swing.tree.TreeSelectionModel;

public class ManualPagesPanel extends javax.swing.JPanel {

  ManualPagesUI parent;
  
  public ManualPagesPanel(ManualPagesUI parent) {
    this.parent = parent;
    initComponents();
    
    // set tree model
    treeView.setModel(parent.model);
    
    // set selection model and listener
    treeView.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
    
    // set HTMLEditorKit 
    HTMLEditorKit kit = new HTMLEditorKit();
    pageView.setEditorKit(kit);
  }   

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    splitPane = new javax.swing.JSplitPane();
    upperScrollPane = new javax.swing.JScrollPane();
    treeView = new javax.swing.JTree();
    LowerScrollPane = new javax.swing.JScrollPane();
    pageView = new javax.swing.JEditorPane();

    splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

    treeView.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
      public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
        treeViewValueChanged(evt);
      }
    });
    upperScrollPane.setViewportView(treeView);

    splitPane.setTopComponent(upperScrollPane);

    pageView.setEditable(false);
    LowerScrollPane.setViewportView(pageView);

    splitPane.setRightComponent(LowerScrollPane);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents

  private void treeViewValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_treeViewValueChanged
    Object item = evt.getPath().getLastPathComponent();
    if (item instanceof ManPage) {
      ManPage page = (ManPage)item;
      pageView.setText(page.getHtml());
    }
  }//GEN-LAST:event_treeViewValueChanged


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane LowerScrollPane;
  private javax.swing.JEditorPane pageView;
  private javax.swing.JSplitPane splitPane;
  private javax.swing.JTree treeView;
  private javax.swing.JScrollPane upperScrollPane;
  // End of variables declaration//GEN-END:variables
}
